# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 770ca24c9cc3842f2b4156a67fb0b95916b0e3e97ba9d03ae66ab8858a3a952ba8dbabd237c34db90b165ae1f1ca7b0398f44f4070a52f549bd8f221039cdd70

test:
  secret_key_base: 6c77065a794786a803d9755c52a66c816d793182caa1c27df28e47d19756b0978cbb3838c441620c48131388643b62c9b75c75a704140bbf8765aace6cbcbce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
